name: Deploy algorithms-js to Pages
on:
  push:
    branches: [ main ]
    paths:
      - 'algorithms-js/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: algorithms-js
      - uses: actions/deploy-pages@v2

